"""Add ON DELETE CASCADE to TeamMember FKs

Revision ID: 4fc11f195bef
Revises: be3624dc00f6
Create Date: 2026-01-14 20:26:38.372437

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4fc11f195bef'
down_revision = 'be3624dc00f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teammember_user_id_fkey'), 'teammember', type_='foreignkey')
    op.create_foreign_key(None, 'teammember', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teammember', type_='foreignkey')
    op.create_foreign_key(op.f('teammember_user_id_fkey'), 'teammember', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
